/*
* generated by Xtext
*/
package org.xtext.nv.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.nv.dsl.services.MMDSLGrammarAccess;

public class MMDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MMDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.nv.dsl.parser.antlr.internal.InternalMMDSLParser createParser(XtextTokenStream stream) {
		return new org.xtext.nv.dsl.parser.antlr.internal.InternalMMDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}
	
	public MMDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MMDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
