/*
 * generated by Xtext
 */
package org.xtext.nv.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MMDSLUiModule extends org.xtext.nv.dsl.ui.AbstractMMDSLUiModule {
	public MMDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
