/*
 * generated by Xtext
 */
package org.xtext.nv.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.nv.dsl.ui.internal.MMDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MMDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MMDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MMDSLActivator.getInstance().getInjector(MMDSLActivator.ORG_XTEXT_NV_DSL_MMDSL);
	}
	
}
