/**
 * generated by Xtext
 */
package org.xtext.nv.dsl.validation;

import org.xtext.nv.dsl.validation.AbstractMMDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MMDSLValidator extends AbstractMMDSLValidator {
}
