/*
* generated by Xtext
*/
package org.xtext.nv.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MMDSLStandaloneSetup extends MMDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new MMDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

