/**
 * generated by Xtext
 */
package org.xtext.nv.dsl.ui.contentassist;

import org.xtext.nv.dsl.ui.contentassist.AbstractMMDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MMDSLProposalProvider extends AbstractMMDSLProposalProvider {
}
