/*
* generated by Xtext
*/
package org.xtext.nv.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MMDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.nv.dsl.ui.internal.MMDSLActivator.getInstance().getInjector("org.xtext.nv.dsl.MMDSL");
	}
	
}
